url = "https://www.supabets.co.za"
top_leagues = "//li/a[contains(text(), 'Top Leagues')]"
home_team = "//a/div[@class='plr_1 ng-binding']"
away_team = "//a/div[@class='plr_2 ng-binding']"
main_markets = "//span[contains(text(), 'Main Markets')]"
gg_h1 = "//div[contains(text(), 'GG 1HT')]/following-sibling::div[@class='oddValue']"
ng_h1 = "//div[contains(text(), 'NG 1HT')]/following-sibling::div[@class='oddValue']"
gg_h2 = "//div[contains(text(), 'GG 2HT')]/following-sibling::div[@class='oddValue']"
ng_h2 = "//div[contains(text(), 'NG 2HT')]/following-sibling::div[@class='oddValue']"
