# .github/workflows/test01.yaml
name: test01
on:
  workflow_dispatch:  
jobs:
  test01:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
     #Setup Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install the necessary packages
        run: pip install -r requirements.txt
      - name: Install Playwright
        run: playwright install
      #- name: Install thefuzz
      #  run: pip install thefuzz
      - name: Run the PytTest script
        run: |
          streamlit run fml.py
          # Example: move screenshots to a dedicated directory
     #     mkdir -p artifacts/screenshots
    #      mv *.png artifacts/screenshots || true
    #  - name: Upload Artifacts
    #    uses: actions/upload-artifact@v2
    #    with:
     #     name: screenshots
     #     path: artifacts/screenshots
