name: test01
on:
  workflow_dispatch:  
jobs:
  test01:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v3
      
      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      
      # Cache Python dependencies
      - name: Cache Python packages
        uses: actions/cache@v3
        id: pip-cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
      
      # Cache Playwright binaries
      - name: Cache Playwright binaries
        uses: actions/cache@v3
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('requirements.txt') }}
      
      # Install the necessary packages
      - name: Install the necessary packages
        run: pip install -r requirements.txt
      
      # Install Playwright (only if not cached)
      - name: Install Playwright
        run: playwright install
        if: steps.playwright-cache.outputs.cache-hit != 'true'
      
      # Run the PyTest script
      - name: Run the PyTest script
        run: |
          pytest -vs
          # Create directories for artifacts
          mkdir -p artifacts/screenshots
          mkdir -p artifacts/logs
          # Move screenshots
          mv *.png artifacts/screenshots || true
          # Move output.txt
          mv output.txt artifacts/logs || true
      
      # Upload Artifacts
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: test-artifacts
          path: |
            artifacts/screenshots
            artifacts/logs/output.txt
